import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CodeVia - Services Provider for Web Development, AI Solutions, and IT Consulting",
  description: "Generated by Web Application ,Software Development Company, IT Solutions, AI Services",
  icons: {
  icon: [
    { url: "https://res.cloudinary.com/dcfzqdk58/image/upload/v1764343258/favicon-16x16_mz9sri.png", sizes: "16x16" },
    { url: "https://res.cloudinary.com/dcfzqdk58/image/upload/v1764343120/favicon-32x32_yz3t9y.png", sizes: "32x32" },
  ],
  shortcut: "https://res.cloudinary.com/dcfzqdk58/image/upload/v1764343297/favicon_yaz1or.ico"
}

};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
